### ISSUE TITLE
Some problems have occurred

### ISSUE THREAD

**Issue by zsirfs** [brianegan/flutter_redux#91]
![image](https://user-images.githubusercontent.com/22249411/47195125-16225b80-d38d-11e8-895a-607f54248c71.png)
![image](https://user-images.githubusercontent.com/22249411/47195137-233f4a80-d38d-11e8-9d0a-9594247448f2.png)
![image](https://user-images.githubusercontent.com/22249411/47195145-2a665880-d38d-11e8-944b-df03f3096909.png)

but: 

```txt
flutter: #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #126    StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #132    ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #136    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #137    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:670:20)
flutter: #138    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #139    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #140    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #141    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #143    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #144    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #145    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Error: No StoreProvider<AppShowTitleState> found. To fix, please try:
flutter: Another exception was thrown: A RenderFlex overflowed by 199288 pixels on the bottom.
```

flutter doctor info:

```
[✓] Flutter (Channel dev, v0.10.0, on Mac OS X 10.14 18A391, locale en-CN)
    • Flutter version 0.10.0 at /Users/zheng/android/flutter
    • Framework revision d954ae6850 (9 days ago), 2018-10-09 16:21:06 -0400
    • Engine revision bf377896ff
    • Dart version 2.1.0-dev.6.0.flutter-a50dfd6698

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/zheng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/zheng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • iPhone X • 6DBBD95F-4D36-47CF-892C-171BFDE35AB4 • ios • iOS 12.0 (simulator)

! Doctor found issues in 1 category.
```

Please help me.

**Comment by zsirfs** [comment]
![image](https://user-images.githubusercontent.com/22249411/47195206-7b764c80-d38d-11e8-9797-39842cb970ee.png)

**Comment by magiccd** [comment]
same problem

**Comment by brianegan** [comment]
Hey all -- did following the instructions help out at all, such as using full package imports? If not, could you please try moving everything but `runApp` outside of `main.dart`.

This bug is often related to this Dart issue: https://github.com/dart-lang/sdk/issues/33076

Until this fix is shipped:

  * don't use relative imports in lib/main.dart
  * don't import lib/main.dart from other files

**Comment by zsirfs** [comment]
![image](https://user-images.githubusercontent.com/22249411/50154329-08913f80-0304-11e9-8a52-fb90f94dd8f4.png)

When I use it like this, prompt for such an error:
![image](https://user-images.githubusercontent.com/22249411/50154390-2d85b280-0304-11e9-973b-8517541296cd.png)

How can I get the store in the component?

**Comment by brianegan** [comment]
Hey there -- was traveling for the holidays. The Store is passed down the Widget tree by an `InheritedWidget`. `InheritedWidgets`, like `Theme` or `StoreProvider` cannot be accessed in the `initState` method, and can only be accessed in the `didChangeDependencies` method.

Therefore, Flutter is reporting that error and letting ya know you can only access the StoreProvider from the `didChangeDependencies` method.
